sudo: required
services:
  - docker

before_install:
  - docker build -t vishwas123v/docker-react -f Dockerfile.dev .


# script:
#   - docker run vishwas123v/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true vishwas123v/docker-react npm run test