sudo: required
services:
  - docker

before_install:
  - docker build -t vishwas123v/docker-react -f Dockerfile.dev .


# script:
#   - docker run vishwas123v/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true vishwas123v/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-893330123209"
  bucket_path: "docker-react"
  on:
    branch: master
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY
